import React from "react";
import FinalYearProjectWebLogin from "../assets/fyp.png";
import FinalYearProjectWeb from "../assets/fyp-ahp.png";

const LittleLemon = () => {
  return (
    <div>
      <div className="flex items-center">
        <a href="/" className="text-3xl font-bold primary-color ml-4 px-5 py-6">
          My Portfolio
        </a>
      </div>
      <div className="bg-[#d43939] h-auto text-white">
        <div className="flex justify-center pb-5">
          <hr className="border-white border-2 w-4/5" />
        </div>
        <div className="flex flex-col justify-center items-center">
          <div className="pt-3 pb-6 text-2xl text-white">
            AHP-Based Learning Application Interface Feature Selection System
          </div>
          <div className="w-2/5 pb-6">
            <hr className="border-white border-2 " />
          </div>
          <div className="flex flex-row gap-6">
            <img
              src={FinalYearProjectWebLogin}
              alt="final-year-project-web"
              className="h-[180px] md:h-[300px]"
            ></img>
            <img
              src={FinalYearProjectWeb}
              alt="final-year-project-web"
              className="h-[180px] md:h-[300px]"
            ></img>
          </div>
        </div>
        <div className="flex flex-row px-[4em] pt-[4em] pb-[1em] gap-4">
          <div className="text-xl">Overview</div>
          <div className=" w-[2px] bg-white relative my-4 mx-auto"></div>

          <div className=" mb-[20px] text-[#d43939] relative bg-white p-6 rounded-3xl max-w-[400px] md:max-w-[600px] sm:max-x-[600px] mx-auto">
            <p className="text-sm md:text-lg py-1">
              As part of my final year project, the AHP-Based Learning
              Application Interface Feature Selection System has been designed
              to identify the most suitable interface features for students with
              learning difficulties. This system integrates the Analytical
              Hierarchy Process (AHP), a Multi-Criteria Decision Making (MCDM)
              approach, to establish feature priorities. Additionally, a Random
              Forest machine learning model will be implemented to validate and
              review the priorities generated by the AHP method.
            </p>
          </div>
        </div>
        <div className="flex justify-center items-center">
          <div className="relative inline-flex group my-3 ">
            <div
              className="absolute transition-all duration-1000 opacity-70 -inset-px bg-gradient-to-r
                    from-[#44BCFF] via-[#FF44EC] to-[#FF675E] rounded-xl blur-lg group-hover:opacity-100
                    group-hover:-inset-1 group-hover:duration-200"
            ></div>
            <a
              href="https://github.com/kalilim269/edu-app-interface-selection"
              target="_blank"
              rel="noopener noreferrer"
              title="View Code"
              role="button"
              className="w-[180px] h-[50px] relative inline-flex items-center justify-center px-8 py-4 text-lg
                    font-bold text-white transition-all duration-200 bg-primary-color font-pj rounded-xl
                    focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-900"
            >
              View Code
            </a>
          </div>
        </div>
      </div>
    </div>
  );
};

export default LittleLemon;
